### ISSUE TITLE
Meltago to MISP server not connecting

### ISSUE THREAD

**Issue by rbcrack** [MISP/MISP-maltego#46]
Getting error  ERROR: Cannot connect to MISP server. Please verify your settings (MISP URL and API key), and ensure the MISP server is reachable from the internet (from entity

But I have got the URL as the IP address and the api key

What am I doing wrong.

**Comment by rbcrack** [comment]
I am Using Windows 10 and everything is installed correctly and MISP is working fine from Maltego I am getting error unable to connect, pleasehelp

**Comment by rbcrack** [comment]
Why is this so difficult to setup with a private MISP server it should be easy to install and use with API.

**Comment by cvandeplas** [comment]
The ATT&CK and MISP from the Maltego transform hub are not compatible with private MISP servers. This is caused by how Paterva designed their transform hub architecture.

You can however install MISP-Maltego locally. It is very easy on a Linux system as documented in the [documentation](https://github.com/MISP/MISP-maltego/blob/master/README.md)
As far as I understand there are issues with Windows, contributions are definitely welcome to fix this !

**Comment by cvandeplas** [comment]
closing as duplicate from issue #33 - windows compatibility for local install

**Comment by lebanonbeirut** [comment]
how to fix ERROR: Cannot connect to MISP server. Please verify your settings (MISP URL and API key), and ensure the MISP server is reachable from the internet
